[[person]]
name = "Sonja Kellner"
role = "Former Team Member "
institution = "LMU Munich & Microsoft"
image = "former_member_photos/Sonja.jpeg"

[[person]]
name = "Srija Mukhopadhyay"
role = "Former Team Member"
institution = "LMU Munich"
image = "former_member_photos/Srija.jpg"

[[person]]
name = "Leah von der Heyde"
role = "Former Team Member"
institution = "LMU Munich"
image = "former_member_photos/Leah.jpg"